# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fstlib_version <- function() {
    .Call(`_fst_fstlib_version`)
}

fststore <- function(fileName, table, compression, uniformEncoding) {
    .Call(`_fst_fststore`, fileName, table, compression, uniformEncoding)
}

fstmetadata <- function(fileName) {
    .Call(`_fst_fstmetadata`, fileName)
}

fstretrieve <- function(fileName, columnSelection, startRow, endRow) {
    .Call(`_fst_fstretrieve`, fileName, columnSelection, startRow, endRow)
}

fsthasher <- function(rawVec, seed, blockHash) {
    .Call(`_fst_fsthasher`, rawVec, seed, blockHash)
}

fstcomp <- function(rawVec, compressor, compression, hash) {
    .Call(`_fst_fstcomp`, rawVec, compressor, compression, hash)
}

fstdecomp <- function(rawVec) {
    .Call(`_fst_fstdecomp`, rawVec)
}

getnrofthreads <- function() {
    .Call(`_fst_getnrofthreads`)
}

setnrofthreads <- function(nrOfThreads) {
    .Call(`_fst_setnrofthreads`, nrOfThreads)
}

hasopenmp <- function() {
    .Call(`_fst_hasopenmp`)
}

restore_after_fork <- function(restore) {
    invisible(.Call(`_fst_restore_after_fork`, restore))
}

