# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fstStore <- function(fileName, table, compression) {
    .Call('fst_fstStore', PACKAGE = 'fst', fileName, table, compression)
}

fstMeta <- function(fileName) {
    .Call('fst_fstMeta', PACKAGE = 'fst', fileName)
}

fstRetrieve <- function(fileName, columnSelection, startRow, endRow) {
    .Call('fst_fstRetrieve', PACKAGE = 'fst', fileName, columnSelection, startRow, endRow)
}

getNrOfActiveThreads <- function() {
    .Call('fst_getNrOfActiveThreads', PACKAGE = 'fst')
}

setNrOfActiveThreads <- function(nrOfThreads) {
    .Call('fst_setNrOfActiveThreads', PACKAGE = 'fst', nrOfThreads)
}

hasOpenMP <- function() {
    .Call('fst_hasOpenMP', PACKAGE = 'fst')
}

