# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

boolToInt <- function(logical) {
    .Call('fst_boolToInt', PACKAGE = 'fst', logical)
}

intToBool <- function(ints) {
    .Call('fst_intToBool', PACKAGE = 'fst', ints)
}

fstStore <- function(fileName, table, compression, serializer) {
    .Call('fst_fstStore', PACKAGE = 'fst', fileName, table, compression, serializer)
}

fstMeta <- function(fileName) {
    .Call('fst_fstMeta', PACKAGE = 'fst', fileName)
}

fstRead <- function(fileName, columnSelection, startRow, endRow) {
    .Call('fst_fstRead', PACKAGE = 'fst', fileName, columnSelection, startRow, endRow)
}

